name: 'github-token-minter action'
description: 'Exchange a GitHub OIDC token for one with elevated privlidges.'
inputs:
  wif_provider:
    description: 'Workload identity federation provider.'
    required: true
  wif_service_account:
    description: 'Workload identity federation service account.'
    required: true
  service_audience:
    description: 'Cloud Run audience for the production github-token-minter service'
    required: true
  service_url:
    description: 'URL for the production github-token-minter service'
    required: true
  requested_permissions:
    description: 'Permission request information in the form {"repositories":["github-token-minter"],"permissions":{"issues":"read"}}'
    required: true
outputs:
  token:
    description: 'Newly minted token'
    value: '${{ steps.mint-token.outputs.token }}'


runs:
  using: 'composite'
  steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
      with:
        workload_identity_provider: '${{ inputs.wif_provider }}'
        service_account: '${{ inputs.wif_service_account }}'
        token_format: 'id_token'
        id_token_audience: '${{ inputs.service_audience }}'
        id_token_include_email: true
    - id: 'mint-token'
      env:
        TOKEN: '${{ steps.auth.outputs.id_token }}'
      uses: actions/github-script@v6
      with:
        script: |
          try {
              const {TOKEN} = process.env;
              const service_url = core.getInput('service_url', { required: true });
              const request_body = core.getInput('requested_permissions', { required: true});
              const id_token = await core.getIDToken('github-token-minter');
              const id_token_value = JSON.parse(id_token).value;
              const response = await fetch(`${service_url}/token`, {
                  method: 'post',
                  body: request_body,
                  headers: {
                      'Content-Type': 'application/json',
                      'X-GitHub-OIDC-Token': id_token_value,
                      'Authorization': `Bearer ${TOKEN}`,
                  }
              });
              const resp = await response.json();
              core.setOutput('token', resp.token);
          }
          catch (err) {
              core.error(`Error requesting token ${err}`);
          }
