# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: 'cli.abcxyz.dev/v1alpha1'
kind: 'Template'

desc: 'Generate the infrastructure necessary to run GitHub Token Minter'

inputs:
  - name: 'custom_name'
    desc: 'A custom name for Github Token Minter'
    default: 'github-token-minter'
  - name: 'subdirectory'
    desc: 'The subdirectory to render the template and the bucket prefix for storing terraform state of GitHub Token Minter'
    default: 'github-token-minter/infra'
  - name: 'project_id'
    desc: 'The Google Cloud project ID to deploy GitHub Token Minter'
    rules:
      - rule: 'gcp_matches_project_id(project_id)'
  - name: 'automation_service_account_member'
    desc: 'The CI service account member for deploying GitHub Token Minter'
  - name: 'domain'
    desc: 'A custom domain for the Google Cloud Load Balancer'
  - name: 'terraform_state_bucket'
    desc: 'The Google Cloud storage bucket for Terraform backend state'
  - name: 'github_owner_id'
    desc: 'The ID of the GitHub owner or organization'

steps:
  - desc: 'Include required files and directories'
    action: 'include'
    params:
      paths: ['contents']
      as: ['{{.subdirectory}}']

  - desc: 'Replace variables'
    action: 'string_replace'
    params:
      paths: ['{{.subdirectory}}']
      replacements:
        - to_replace: 'REPLACE_CUSTOM_NAME'
          with: '{{.custom_name}}'
        - to_replace: 'REPLACE_MODULE_NAME'
          with: '{{toLowerSnakeCase .custom_name}}'
        - to_replace: 'REPLACE_PROJECT_ID'
          with: '{{.project_id}}'
        - to_replace: 'REPLACE_DOMAIN'
          with: '{{.domain}}'
        - to_replace: 'REPLACE_BUCKET_NAME'
          with: '{{.terraform_state_bucket}}'
        - to_replace: 'REPLACE_BUCKET_PREFIX'
          with: '{{.subdirectory}}'
        - to_replace: 'REPLACE_AUTOMATION_SERVICE_ACCOUNT_MEMBER'
          with: '{{.automation_service_account_member}}'
        - to_replace: 'REPLACE_GITHUB_OWNER_ID'
          with: '{{.github_owner_id}}'
