# abcxyz/breakglass.yaml
id: 'abcxyz/breakglass'
permissions:
  - if: jwt.workflow == 'Test' && jwt.actor == 'verbanicm'
    repos:
      - "*"
    scopes:
      - "issues:read"
      - "pull_request:write"

  # catch-all
  - if: true
    repos:
      - "abcxyz/breakglass"
    scopes:
      - "issues:read"