# abcxyz/breakglass.yaml
- 
  if: |-
    assertion.workflow_ref.startsWith("abcxyz/breakglass/.github/workflows/breakglass.yml") &&
    assertion.event_name == 'issues'
  repositories: []
  permissions:
    members: 'write'
- 
  if: |-
    assertion.workflow_ref.startsWith("abcxyz/breakglass/.github/workflows/cleanup.yml") &&
    assertion.event_name == 'schedule' &&
    assertion.ref == 'refs/head/main'
  repositories: []
  permissions:
    members: 'write'
