# abcxyz/breakglass.yaml
id: 'abcxyz/breakglass'
permissions:
  - if: 'attribute.workflow == "Test" && actor == "verbanicm"'
    repos:
      - '*'
    scopes:
      - 'issues:read'
      - 'pull_request:write'

  # catch-all
  - if: 'true'
    repos:
      - 'abcxyz/breakglass'
    scopes:
      - 'issues:read'