# abcxyz/github-token-minter.yaml
- 
  if: 'assertion.workflow_ref.startsWith("abcxyz/github-token-minter/.github/workflows/integration.yml")'
  respositories: ['github-token-minter']
  permissions:
    issues: 'read'
