# abcxyz/guardian.yaml
- if: |-
    assertion.workflow_ref.startsWith("abcxyz/guardian/.github/workflows/test-admin.yml") ||
    assertion.workflow_ref.startsWith("abcxyz/guardian/.github/workflows/test-apply.yml") ||
    assertion.workflow_ref.startsWith("abcxyz/guardian/.github/workflows/test-plan.yml")
  repositories:
    - 'guardian'
    - 'infra'
  permissions:
    contents: 'read'
