# abcxyz/infra.yaml
- if: |-
    assertion.workflow_ref.startsWith("abcxyz/infra/.github/workflows/terraform.yml") &&
    assertion.job_workflow_ref.startsWith("abcxyz/pkg/.github/workflows/terraform-lint.yml")
  respositories:
    - 'abcxyz/github-metrics-aggregator'
    - 'abcxyz/github-token-minter'
    - 'abcxyz/guardian'
    - 'abcxyz/infra'
    - 'abcxyz/jvs'
    - 'abcxyz/lumberjack'
    - 'abcxyz/pmap'
  permissions:
    contents: 'read'
