# abcxyz/infra.yaml
- if: 'assertion.workflow_ref.startsWith("abcxyz/infra/.github/workflows/terraform.yml")'
  repositories:
    - 'github-metrics-aggregator'
    - 'github-token-minter'
    - 'guardian'
    - 'infra'
    - 'jvs'
    - 'lumberjack'
    - 'pmap'
  permissions:
    contents: 'read'
