# abcxyz/secure-setup-terraform.yaml
config:
  - if: |-
      assertion.workflow_ref.startsWith("abcxyz/secure-setup-terraform/.github/workflows/update-checksums.yml")
      assertion.event_name == 'schedule' &&
      assertion.ref == 'refs/head/main'
    repositories:
      - 'abcxyz/secure-setup-terraform'
    permissions:
      pull_request: 'write'
