name: 'ci'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
env:
  DOCKER_REGISTRY: 'us-docker.pkg.dev'
  DOCKER_TAG: '${{ github.sha }}'
  DOCKER_REPO: 'us-docker.pkg.dev/github-token-minter-ci/ci-images'
  IMAGE_NAME: 'github-token-minter-server'
  WIF_PROVIDER: 'projects/30971435804/locations/global/workloadIdentityPools/github-pool-8d5d/providers/github-provider'
  WIF_SERVICE_ACCOUNT: 'github-token-minter-8d5d-ci-sa@github-token-minter-ci.iam.gserviceaccount.com'
  SERVICE_NAME: 'github-token-minter-4b03'
  SERVICE_URL: 'https://github-token-minter-4b03-czzqdawzea-uc.a.run.app'
  PROJECT_ID: 'github-token-minter-ci'
  REGION: 'us-central1'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  # Linting jobs - go
  go_lint:
    uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@main' # ratchet:exclude
    with:
      go_version: '1.19'
  # Unit tests - go
  go_test:
    uses: 'abcxyz/pkg/.github/workflows/go-test.yml@main' # ratchet:exclude
    with:
      go_version: '1.19'
  lint_and_unit:
    runs-on: 'ubuntu-latest'
    needs:
      - 'go_lint'
      - 'go_test'
    steps:
      - run: 'echo prechecks complete'
  # Build the main github-token-minter server and push to artifact registry
  build-github-token-minter-server:
    runs-on: 'ubuntu-latest'
    needs:
      - 'lint_and_unit'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b' # ratchet:actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'
      - name: 'Authenticate to Artifact Registry'
        uses: 'docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a' # ratchet:docker/login-action@v2
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.DOCKER_REGISTRY }}'
      - name: 'Build the main server container and push to the registry'
        uses: 'docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5' # ratchet:docker/build-push-action@v3
        with:
          push: true
          tags: '${{ env.DOCKER_REPO }}/github-token-minter-server:${{ env.DOCKER_TAG }}'
          file: 'Dockerfile'
  build:
    runs-on: 'ubuntu-latest'
    needs:
      - 'build-github-token-minter-server'
    steps:
      - run: 'echo build complete'

  deployment:
    runs-on: 'ubuntu-latest'
    needs:
      - 'build'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' # ratchet:google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'
      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce' # ratchet:google-github-actions/setup-gcloud@v1
      - name: 'Deploy to Cloud Run'
        run: |-
          gcloud run services update ${{ env.SERVICE_NAME }} \
            --project="${{ env.PROJECT_ID }}" \
            --region="${{ env.REGION }}" \
            --image="${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}"

  integration:
    runs-on: 'ubuntu-latest'
    needs:
      - 'deployment'
    permissions:
      contents: 'write'
      packages: 'write'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' # ratchet:actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@c4799db9111fba4461e9f9da8732e5057b394f72' # ratchet:google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'id_token'
          id_token_audience: '${{ env.SERVICE_URL }}'
          id_token_include_email: true

      - id: "mint-token"
        env:
          token: ${{ steps.auth.outputs.id_token }}
        run: |
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=github-token-minter" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          echo ${OIDC_TOKEN}

          JWT=$(echo $OIDC_TOKEN | jq -j '.value')
          echo ${JWT}

          APP_TOKEN=$(curl -X POST -d'{"repositories":["github-token-minter"],"permissions":{"issues":"read"}}' \
            -H "Authorization: Bearer ${{env.token}}" \
            -H "X-GitHub-OIDC-Token: ${JWT}" \
            ${{ env.SERVICE_URL}}/token)
          echo ${APP_TOKEN}

          TOKEN=$(echo ${APP_TOKEN} | jq -j '.token')

          curl --fail \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/abcxyz/github-token-minter/issues/events
