name: 'test github sha'

on:
  pull_request:
    branches:
      - 'main'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Percy snapshot test'
        run: 'echo $GITHUB_SHA'


